### ISSUE TITLE
Kanban Boards

### ISSUE THREAD

**Issue by TracK92** [TracK92/doctor-appointment-api#9]
- Number of Team Members - 4
        - @digia3d 
        - @TracK92 
        - @brahimdidi 
        - @AbbyNyakara 
- Backend Kanban Board
        - Follow [this link](https://github.com/users/TracK92/projects/8/views/1) to the backend kanban board
      
![image](https://user-images.githubusercontent.com/40690789/203585377-46e3edd5-0f70-45aa-96a2-311e0980c102.png)

- Frontend Kanban Board
        - Follow [this link](https://github.com/users/TracK92/projects/9/views/1) to the frontend kanban board
      
![image](https://user-images.githubusercontent.com/40690789/203585727-0e54fc63-79ab-45b8-9906-8cda92cd0c60.png)

**Comment by Meltrust** [comment]
Hi @TracK92,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All tasks are pointed✔️ 
- Pointing is fear✔️ 
- All tasks have descriptions✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
